### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by lxbarth** [hotosm/learnosm#40]
Here's my launch list for getting the first iteration of learnosm.org live. This will be a minimal version, focused on relaunching the most important content, linking to further content on Wiki. I think this will be fine for now, please let me know if not.

@wonderchook @MappingKat @jueyang - please let me know if you're seeing something missing here.
- [x] @jueyang #33 design review
- [x] @jueyang #29 Friday night review 
- [x] @jueyang #41 Add BNPB Logo
- [x] @lxbarth #38 @learnosm 
- [x] @lxbarth #39 Switching domain
- [ ] @MappingKat @lxbarth Line up blog posts for hot.openstreetmap.org and mapbox.com
